services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
        # Bluetooth
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  music-assistant-server:
    image: ghcr.io/music-assistant/server:beta
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    depends_on: 
      - pihole
    volumes:
      - ./config/music-assistant-server/data:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info
  lms:
    profiles:
      # we exchanged the LMS by music-assistant at 2024-12
      - disabled
    container_name: lms
    image: lmscommunity/logitechmediaserver
    volumes:
      - ./config/lms/config:/config:rw
      - ./config/lms/music:/music:ro
      - ./config/lms/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9000:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
        # spotty plugin (https://forums.slimdevices.com/showthread.php?113657-Spotty-4-4-6-and-Docker-on-NAS-not-working&p=1004093&viewfull=1#post1004093)
        #- 5353:5353/udp
    restart: unless-stopped
  squeezelite:
    image: giof71/squeezelite:daily-debian-full-squeezelite-current-sourceforge
    container_name: squeezelite
    depends_on: 
      - music-assistant-server
    devices:
      - /dev/snd:/dev/snd
    environment:
      #- PRESET=super-amazing-dac,archimago-goldilocks,rates_up_to_384k
      - SQUEEZELITE_AUDIO_DEVICE=default:CARD=Generic
      - SQUEEZELITE_NAME=lite
      - SQUEEZELITE_SERVER_PORT=music-assistant-server
      - DISPLAY_PRESETS=N
      # random generated but stable
      - SQUEEZELITE_MAC_ADDRESS=67:87:13:14:da:fe
      - DISABLE_MAC_ADDRESS_GENERATION=yes
    volumes:
      - ./config/squeezelite/config/additional.conf:/app/assets/additional-presets.conf
    restart: unless-stopped
  candle:
    container_name: candle
    image: ghcr.io/unividuell/candle:ha
    depends_on:
      - music-assistant-server
    ports:
      - 9002:8080
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'Europe/Berlin'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: '6LQ-cTZc'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
      - ./config/pihole:/etc/pihole
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      #- NET_ADMIN
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - 8000:8000 # welcome
      - 8008:8008 # up?
      - 9001:9001
    volumes:
      - caddy_data:/data
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/log:/var/log
      - $PWD/caddy/welcome:/srv/welcome

volumes:
  caddy_data:
    external: true
