version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
        # Bluetooth
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  lms:
    container_name: lms
    image: lmscommunity/logitechmediaserver
    volumes:
      - ./config/lms/config:/config:rw
      - ./config/lms/music:/music:ro
      - ./config/lms/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9000:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
        # spotty plugin (https://forums.slimdevices.com/showthread.php?113657-Spotty-4-4-6-and-Docker-on-NAS-not-working&p=1004093&viewfull=1#post1004093)
        #- 5353:5353/udp
    restart: unless-stopped
  squeezelite:
    image: giof71/squeezelite:latest
    container_name: squeezelite
    depends_on: 
      - "lms"
    devices:
      - /dev/snd:/dev/snd
    environment:
      #- PRESET=super-amazing-dac,archimago-goldilocks,rates_up_to_384k
      - SQUEEZELITE_AUDIO_DEVICE=default:CARD=Generic
      - SQUEEZELITE_NAME=lite
      - SQUEEZELITE_SERVER_PORT=lms
      - DISPLAY_PRESETS=N
    volumes:
      - ./config/squeezelite/config/additional.conf:/app/assets/additional-presets.conf
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
      #network_mode: host
    volumes:
      - ./config/adguard/work:/opt/adguardhome/work
      - ./config/adguard/conf:/opt/adguardhome/conf
    ports:
      # DNS
      - 53:53/tcp
      - 53:53/udp
      # DHCP
      - 67:67/udp
      - 68:68/udp
      # admin ui / HTTPS/DNS-over-HTTPS
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      # DNS-over-TLS
      - 853:853/tcp
      # DNS-over-QUIC
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      # DNSCrypt
      - 5443:5443/tcp
      - 5443:5443/udp
  pihole:
    profiles:
      - pihole
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    network_mode: host
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: '6LQ-cTZc'
    # Volumes store your data between container upgrades
    volumes:
      - ./config/pihole:/etc/pihole
      - ./config/pihole/dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
